# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/distros/alpine/change_hostname.yml
---
- name: change hostname
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/distros/alpine/change_hostname.yml"
    hostname: "services"
  tasks:
  - name: Set hostname on Alpine
    ansible.builtin.hostname:
      name: "{{ hostname }}"
      use: redhat

  - name: Update /etc/hostname
    ansible.builtin.copy:
      content: "{{ hostname }}"
      dest: /etc/hostname

  - name: Update /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 {{ hostname }} localhost"
      regexp: '^127\.0\.0\.1'

