version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx:/data
      - /home/skylord/docker/nginx/letsencrypt:/etc/letsencrypt

volumes:
  nginx:
