---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist