---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no  # Disable gathering facts
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
    
    - name: Install packages
      apt:
        name:
          - docker
          - docker-compose
        state: present
    
    - name: Disable Docker service from starting at boot
      systemd:
        name: docker
        enabled: no

    - name: Check if the flag file exists
      stat:
        path: /ansible/ansible_first_run.flag
      register: flag_file

    # - name: Perform tasks for the first run
    #   debug:
    #     msg: "This is the first Ansible run"
    #   when: flag_file.stat.exists == false
    - name: Create directory recursively
      file:
        path: /mnt/data
        state: directory
        recurse: yes

    - name: Set permissions and ownership on the mount point directory
      file:
        path: /mnt/data  
        owner: skylord  
        group: skylord  
        mode: "0777"  

    - name: Mount the volume
      mount:
        path: /mnt/data 
        src: /dev/sdb1  # Replace with your actual device
        fstype: ext4    # Replace with the file system type
        opts: defaults
        state: mounted

    - name: Create directory /opt/dockge
      file:
        path: /opt/dockge
        state: directory
        owner: skylord  
        group: skylord  
        mode: "0755"  

    - name: Create Dockge Docker volume
      docker_volume:
        name: dockge_data

    - name: Deploy Dockge Container
      docker_container:
        name: dockge
        image: louislam/dockge:1
        state: started
        restart_policy: unless-stopped
        detach: yes
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - dockge_data:/app/data
          - /mnt/data/docker/compose:/mnt/data/docker/compose
        env:
          DOCKGE_STACKS_DIR: /mnt/data/docker/compose
        container_default_behavior: 'compatibility'

    - name: Create Docker volume
      docker_volume:
        name: portainer_data
    
    - name: Run Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        detach: yes
        restart_policy: always
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"
        container_default_behavior: 'compatibility'

    - name: Start Docker service
      systemd:
        name: docker
        state: started
    
    - name: Install Tailscale using one-liner command
      shell: |
        curl -fsSL https://tailscale.com/install.sh | sh
    
    - name: Create the flag file
      file:
        path: /ansible/ansible_first_run.flag
        state: touch
      when: flag_file.stat.exists == false
