# ubuntu
---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/ubuntu.yml"
    ansible_flag_path: "/ansible/ansible_first_run.flag"

  tasks:
    - name: Install packages
      apt:
        name:
          - nfs-kernel-server
        state: present
        update_cache: yes
    
    - name: Schedule playbook to run every 5 minutes
      cron:
        name: "Run Ansible playbook every 5 minutes with logging"
        job: "/usr/bin/ansible-pull -v -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-pull.log 2>&1"
        minute: "*/5"
        state: present

    - name: Schedule playbook to run at reboot with logging
      cron:
        name: "Run Ansible playbook at reboot with logging"
        job: "/usr/bin/ansible-pull -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-pull.log 2>&1"
        special_time: "reboot"
        state: present


    - name: Check if the flag file exists
      stat:
        path: "{{ ansible_flag_path }}"
      register: flag_file


    - name: Create NFS export directory
      file:
        path: /var/nfs/shared
        state: directory
        mode: '0755'
    

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: '/var/nfs/shared *(rw,sync,no_subtree_check)'
        create: yes


    - name: Restart NFS server
      systemd:
        name: nfs-kernel-server
        state: restarted
    

    - name: Create the flag file
      file:
        path: "{{ ansible_flag_path }}"
        state: touch
      when: flag_file.stat.exists == false


