---
- import_playbook: ../apt/u_u.yml # update and upgrade
- import_playbook: set_facts.yml
- import_playbook: ../docker/install.yml 
  when: flag_file_exists == false
- import_playbook: ../docker/dockge.yml
- import_playbook: nfs.yml 
  when: flag_file_exists == false
- import_playbook: ../cron/main_playbook.yml


- name: main playbook
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - /ansible/
      when: flag_file_exists == false

    - name: Create the flag file
      ansible.builtin.file:
        path: "{{ ansible_flag_path }}"
        state: touch
      when: flag_file_exists == false