---
- name: Set global facts
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Check if the flag file exists
      ansible.builtin.stat:
        path: "/ansible/ansible_first_run.flag"
      register: flag_file

    - name: Set fact for all hosts
      set_fact:
        flag_file_exists: flag_file.stat.exists
        git_repo_url: "https://github.com/truedem0n/homelab.git"
        ansible_playbook_path: "prod/ansible/lubuntu/main.yml"
        ansible_flag_path: "/ansible/ansible_first_run.flag"
      delegate_facts: true