---
- name: Setup dockge
  hosts: localhost

  tasks:
    - name: Deploy Dockge Container
      docker_container:
        name: dockge
        image: louislam/dockge:latest
        state: started
        restart_policy: always
        detach: yes
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /mnt/data/docker/containers/dockge/app/data:/app/data
          - /home/skylord/docker_compose/:/docker_compose
        container_default_behavior: 'compatibility'
        env:
          DOCKGE_STACKS_DIR: /docker_compose