---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - homer:/www/assets
    ports:
      - 8085:8080
    user: 1000:1000 # default

volumes:
  homer:
