version: '3'

services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - firefox:/config
    network_mode: "service:vpn"
    shm_size: "1gb"
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - /home/skylord/docker/qbittorrent/downloads:/downloads
    network_mode: "service:vpn"
    restart: unless-stopped

  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    environment:
      - VPN_SERVICE_PROVIDER=vpn_provider
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - SERVER_CITIES=Montréal
    cap_add:
      - NET_ADMIN
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:


volumes:
  firefox:
  qbittorrent: