# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/vms/debian.yml
---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/vms/debian.yml"
    ansible_flag_path: "/ansible/ansible_first_run.flag"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Check if the flag file exists
      stat:
        path: "{{ ansible_flag_path }}"
      register: flag_file

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - /ansible/
        - /mnt/data
      when: flag_file.stat.exists == false
    
    - name: Create the flag file
      file:
        path: "{{ ansible_flag_path }}"
        state: touch
      when: flag_file.stat.exists == false
    
    - name: Install packages (debian)
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Get distribution codename
      command: lsb_release -cs
      register: dist_codename

    - name: Add Docker repository to Apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ dist_codename.stdout }} stable"
        create: yes

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - nfs-common
          - nfs4-acl-tools
        state: present

    - name: Check if the flag file exists
      stat:
        path: "{{ ansible_flag_path }}"
      register: flag_file

    - name: Schedule playbook to run every 5 minutes
      cron:
        name: "Run Ansible playbook every 5 minutes with logging"
        job: "/usr/bin/ansible-pull -v -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-pull.log 2>&1"
        minute: "*/5"
        state: present

    - name: Schedule playbook to run at reboot with logging
      cron:
        name: "Run Ansible playbook at reboot with logging"
        job: "/usr/bin/ansible-pull -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-pull.log 2>&1"
        special_time: "reboot"
        state: present

    - name: Schedule docker system prune all
      cron:
        name: "Run docker system prune with logging"
        job: "/usr/bin/docker system prune -af > /var/log/docker-prune.log 2>&1"
        special_time: "daily"
        state: present

    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch

    
    - name: Add NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.26:/data/ /mnt/data nfs rw,sync,hard 0 0"
        state: present

    - name: Print link to local IP with port 5001
      ansible.builtin.debug:
        msg: "Dockge: http://{{ ansible_default_ipv4.address }}:5001"

    - name: Reboot immediately if there was a change
      ansible.builtin.command: /sbin/reboot
      when: flag_file.stat.exists == false
    
    
    - name: Print link to local IP with port 5001
      ansible.builtin.debug:
        msg: "Dockge: http://{{ ansible_default_ipv4.address }}:5001"
    
    - name: Ensure Docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      when: flag_file.stat.exists == true
    
    # instead do it via crontab daily
    # - name: Prune unused Docker data
    #   docker_prune:
    #     containers: true
    #     images: true
    #     networks: true
    #     volumes: true
    #     builder_cache: true
    #   register: prune_output
    #   when: flag_file.stat.exists == true
