---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/vms/vpn.yml"
    ansible_flag_path: "/ansible/ansible_first_run.flag"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Check if the flag file exists
      stat:
        path: "{{ ansible_flag_path }}"
      register: flag_file

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - /ansible/
        - /mnt/data
      when: flag_file.stat.exists == false
    
    - name: Install packages (ubuntu)
      apt:
        name:
          - docker
          - docker-compose
          - nfs-common
          - nfs4-acl-tools
        state: present

    - name: Schedule playbook to run every 5 minutes
      cron:
        name: "Run Ansible playbook every 5 minutes with logging"
        job: "/usr/bin/ansible-pull -v -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-pull.log 2>&1"
        minute: "*/5"
        state: present

    - name: Schedule playbook to run at reboot with logging
      cron:
        name: "Run Ansible playbook at reboot with logging"
        job: "/usr/bin/ansible-pull -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-pull.log 2>&1"
        special_time: "reboot"
        state: present


    - name: Deploy Dockge Container
      docker_container:
        name: dockge
        image: louislam/dockge:latest
        state: started
        restart_policy: always
        detach: yes
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /mnt/data/docker/containers/dockge/app/data:/app/data
          - /mnt/data/docker/compose:/mnt/data/docker/compose
        container_default_behavior: 'compatibility'
        env:
          DOCKGE_STACKS_DIR: /mnt/data/docker/compose

    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch

    
    - name: Add NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.26:/data/ /mnt/data nfs rw,sync,hard 0 0"
        state: present

    - name: Print link to local IP with port 5001
      ansible.builtin.debug:
        msg: "Dockge: http://{{ ansible_default_ipv4.address }}:5001"

    - name: Create the flag file
      file:
        path: "{{ ansible_flag_path }}"
        state: touch
      when: flag_file.stat.exists == false

    - name: Reboot immediately if there was a change
      ansible.builtin.command: /sbin/reboot
      when: flag_file.stat.exists == false
    
    
    - name: Print link to local IP with port 5001
      ansible.builtin.debug:
        msg: "Dockge: http://{{ ansible_default_ipv4.address }}:5001"
