# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/docker.yml
---
- name: Install Docker using official convenience script
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    ansible_user: skylord

  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
        state: present
        update_cache: true

    - name: Download and run Docker install script
      shell: curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash

    - name: Create docker group (if it doesn't exist)
      group:
        name: docker
        state: present

    - name: Add current user to docker group (optional)
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Warn user to re-login for Docker group to apply
      debug:
        msg: |
          ✅ Docker installed.
          🔁 Please **log out and log back in** (or reboot)
          so that '{{ ansible_user }}' can run `docker` without sudo.
