# backup 
# This command pulls the latest version of the playbook from the GitHub repository and executes it
# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/dr.yml
---
- name: DR
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/dr.yml"
    ansible_flag_path: "/ansible/restic.flag"
    restic_lib_path: "/var/lib/restic"
    source_dir: /mnt/backups/partial-backup
    backup_dir: /mnt/dropbox 
    rotate_count: 5

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - restic
          - curl
          - bash
          - rclone
          - fuse3
        state: present

    - name: Check if the flag file exists
      stat:
        path: "{{ ansible_flag_path }}"
      register: flag_file
    
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - /var/lib/restic
        - /mnt/backups
        - /mnt/dropbox
  
    - name: Create the flag file
      file:
        path: "{{ ansible_flag_path }}"
        state: touch
      when: flag_file.stat.exists == false

    - name: Add secondary NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.24:/var/nfs/shared /mnt/backups nfs ro,sync,hard 0 0"
        state: present
    
    - name: Add primary NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.26:/data/ /mnt/data nfs ro,sync,hard 0 0"
        state: present
    
    - name: End play if condition is met
      meta: end_play
      when: flag_file.stat.exists == false



    - name: Create and rotate tar backups
      block:
        - name: Create timestamp variable
          set_fact:
            timestamp: "{{ ansible_date_time.date }}"

        - name: Create tar backup
          archive:
            path: "{{ source_dir }}"
            dest: "{{ backup_dir }}/backup-{{ timestamp }}.tar.gz"
            format: gz

        - name: Find old backups
          find:
            paths: "{{ backup_dir }}"
            patterns: "backup-*.tar.gz"
            file_type: file
          register: backup_files

        - name: Sort backups by modification time
          set_fact:
            sorted_backups: "{{ backup_files.files | sort(attribute='mtime', reverse=true) }}"

        - name: Remove old backups
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ sorted_backups[5:] }}"
          when: sorted_backups|length > 5




    - name: Schedule playbook to run daily
      cron:
        name: "Run b2 backup playbook every 5 minutes with logging"
        job: "/usr/bin/ansible-pull -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-dr.log 2>&1"
        special_time: "daily"
        state: present
      when: flag_file.stat.exists

    - name: Schedule playbook to run at reboot with logging
      cron:
        name: "Run b2 backup playbook at reboot with logging"
        job: "/usr/bin/ansible-pull -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible-dr.log 2>&1"
        special_time: "reboot"
        state: present
      when: flag_file.stat.exists

    - name: Schedule playbook to run at reboot with logging
      cron:
        name: "Run b2 backup playbook at reboot with logging"
        job: "nohup /usr/bin/rclone mount dropbox:/Restic /mnt/dropbox/ --vfs-cache-mode writes --allow-other > /var/log/rclone.log 2>&1 &"
        special_time: "reboot"
        state: present
      when: flag_file.stat.exists == true

    
    