# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/mount_local_vols.yml
---
- name: mount local vols on nuc
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/mount_local_vols.yml"

  tasks:

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: yes
      loop:
        - /mnt/media
        - /mnt/backups

    - name: Configure permanent mount
      ansible.posix.mount:
        src: /dev/sdb1 # dwo tb di
        path: /mnt/media
        fstype: exfat
        opts: "defaults,uid=1000,gid=1000,umask=000"
        state: mounted
    
    - name: Configure second permanent mount
      ansible.posix.mount:
        src: /dev/sdc1 # dwo tb di
        path: /mnt/backups
        fstype: exfat
        opts: "defaults,uid=1000,gid=1000,umask=000"
        state: mounted