# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/primary_nfs.yml
---
- name: Update and upgrade Alpine packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/primary_nfs.yml"
    ansible_flag_path: "/ansible/ansible_first_run.flag"

  tasks:

    - name: Install package based on distribution
      package:
        name: "{{ pkg_names[ansible_facts['distribution']] }}"
        state: present
      vars:
        pkg_names:
          Debian: nfs-common
          Alpine: nfs-utils
      when: ansible_facts['distribution'] in pkg_names

    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch

    - name: Add NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.26:/data/ /mnt/data nfs rw,sync,hard 0 0"
        state: present

    - name: Trigger reboot with 5 second delay
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0