# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/primary_nfs.yml
---
- name: Update and upgrade Alpine packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/primary_nfs.yml"
    ansible_flag_path: "/ansible/ansible_first_run.flag"

  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - nfs-utils
        state: present

    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch

    - name: Add NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.26:/data/ /mnt/data nfs rw,sync,hard 0 0"
        state: present

    - name: Ensure nfsmount is active
      ansible.builtin.service:
        name: nfsmount
        state: started
        enabled: yes