# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/primary_nfs.yml
---
- name: Update and upgrade packages locally
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/primary_nfs.yml"
    ansible_flag_path: "/ansible/ansible_first_run.flag"
    nfs_packages:
      Debian: nfs-common
      Alpine: nfs-utils
    nfs_services:
      Debian: nfs-client.target
      Alpine: nfsmount

  tasks:
    - name: Print ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
        
    - name: Install NFS package based on distribution
      package:
        name: "{{ nfs_packages[ansible_facts['distribution']] }}"
        state: present
      when: ansible_facts['distribution'] in nfs_packages

    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch

    - name: Add NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.26:/data/ /mnt/data nfs rw,sync,hard 0 0"
        state: present

    - name: Ensure NFS service is active
      ansible.builtin.service:
        name: "{{ nfs_services[ansible_facts['distribution']] }}"
        state: started
        enabled: yes
      when: ansible_facts['distribution'] in nfs_services

    - name: Trigger reboot with 5 second delay
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: ansible_facts['distribution'] == Debian
