# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/rsync.yml
---
- name: rsync
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/rsync.yml"
    ansible_flag_path: "/ansible/rsync_first_run.flag"
    source_path: "/var/lib/docker/volumes"
    dest_path: "/mnt/data/docker/docker_volumes/"

  tasks:
    - name: Create log directory
      file:
        path: /var/log/rsync
        state: directory
        mode: '0755'
    
    - name: Ensure rsync is installed
      ansible.builtin.package:
        name:
          - rsync
        state: present

    - name: Sync directories
      ansible.builtin.shell: |
        rsync -avz --progress --exclude='dockge_dockge' \
        --log-file=/var/log/rsync.log \
        {{ source_path }} {{ dest_path }}

    - name: Schedule playbook to run every 5 minutes
      cron:
        name: "Run rsync playbook every 8 hours with logging"
        job: "/usr/bin/ansible-pull -v -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible/rsync-ansible-pull.log 2>&1"
        hour: "*/8"
        state: present