# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/rsync.yml
---
- name: rsync
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    git_repo_url: "https://github.com/truedem0n/homelab.git"
    ansible_playbook_path: "prod/ansible/playbooks/rsync.yml"
    ansible_flag_path: "/ansible/rsync_first_run.flag"
    source_path: "/var/lib/docker/volumes"
    dest_path_prefix: "/mnt/data/docker"

  tasks:
    - name: Create log directory
      file:
        path: /var/log/rsync
        state: directory
        mode: '0755'
    
    - name: Ensure rsync is installed
      ansible.builtin.package:
        name:
          - rsync
        state: present
    
    - name: Fetch hostname
      ansible.builtin.command: hostname
      register: host_name_output

    - name: Sync directories
      ansible.builtin.shell: |
        rsync -avz --progress --exclude='dockge_dockge' \
        --exclude='backingFsBlockDev' \
        --log-file=/var/log/rsync.log \
        "{{ source_path }}" "{{ dest_path_prefix }}/{{ host_name_output.stdout }}/docker_volumes" --delete

    - name: Schedule playbook to run every 8 hours
      cron:
        name: "Run rsync playbook every 8 hours with logging"
        job: "/usr/bin/ansible-pull -v -U {{ git_repo_url }} {{ ansible_playbook_path }} > /var/log/ansible/rsync-ansible-pull.log 2>&1"
        hour: "*/8"
        state: present