# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/wireguard.yml
---
- name: setup wireguard
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    interface_name: wg0
    wireguard_address: "10.8.0.1/24"
    listen_port: 51820
    external_interface: eth0 # change if not eth0

    wireguard_peers:
      - name: phone
        public_key: "CLIENT_PUBLIC_KEY_1"
        allowed_ip: "10.8.0.2/32"
      - name: laptop
        public_key: "CLIENT_PUBLIC_KEY_2"
        allowed_ip: "10.8.0.3/32"

  tasks:
    - name: Install packages
      apt:
        name:
          - wireguard
          - wireguard-tools
          - iptables-persistent
        state: present
        update_cache: yes

    - name: Create WireGuard config directory
      file:
        path: /etc/wireguard
        state: directory
        mode: "0700"

    - name: Generate private key
      command: wg genkey
      register: private_key
      changed_when: true

    - name: Save private key
      copy:
        content: "{{ private_key.stdout }}"
        dest: /etc/wireguard/privatekey
        mode: "0600"

    - name: Generate public key from private key
      shell: echo "{{ private_key.stdout }}" | wg pubkey
      register: public_key
      changed_when: true

    - name: Create wg0.conf
      copy:
        dest: "/etc/wireguard/{{ interface_name }}.conf"
        mode: "0600"
        content: |
          [Interface]
          Address = {{ wireguard_address }}
          ListenPort = {{ listen_port }}
          PrivateKey = {{ private_key.stdout }}
          PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ external_interface }} -j MASQUERADE
          PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ external_interface }} -j MASQUERADE

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Start and enable WireGuard service
      systemd:
        name: "wg-quick@{{ interface_name }}"
        enabled: yes
        state: started

    - name: Save iptables rules
      command: netfilter-persistent save

    - name: Add WireGuard peers to config
      blockinfile:
        path: "/etc/wireguard/{{ interface_name }}.conf"
        block: |
          [Peer]
          PublicKey = {{ item.public_key }}
          AllowedIPs = {{ item.allowed_ip }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      loop: "{{ wireguard_peers }}"

    - name: Restart WireGuard to apply peer changes
      systemd:
        name: "wg-quick@{{ interface_name }}"
        state: restarted
