# /usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/playbooks/wireguard.yml
---
- name: setup wireguard
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    interface_name: wg0
    wireguard_address: "10.8.0.1/24"
    listen_port: 51820
    external_interface: ens5

  tasks:
    - name: Install packages
      apt:
        name:
          - wireguard
          - wireguard-tools
          - iptables-persistent
          - qrencode
        state: present
        update_cache: yes

    - name: Create WireGuard config and clients directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0700"
      loop:
        - /etc/wireguard
        - /etc/wireguard/clients

    - name: Generate private key
      command: wg genkey
      register: private_key
      changed_when: true

    - name: Save private key
      copy:
        content: "{{ private_key.stdout }}"
        dest: /etc/wireguard/privatekey
        mode: "0600"

    - name: Generate public key from private key
      shell: echo "{{ private_key.stdout }}" | wg pubkey
      register: public_key
      changed_when: true

    - name: Save public key
      copy:
        content: "{{ public_key.stdout }}"
        dest: /etc/wireguard/publickey
        mode: "0600"

    - name: Create wg0.conf
      copy:
        dest: "/etc/wireguard/{{ interface_name }}.conf"
        mode: "0600"
        content: |
          [Interface]
          Address = {{ wireguard_address }}
          ListenPort = {{ listen_port }}
          PrivateKey = {{ private_key.stdout }}
          PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ external_interface }} -j MASQUERADE
          PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ external_interface }} -j MASQUERADE

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Start and enable WireGuard service
      systemd:
        name: "wg-quick@{{ interface_name }}"
        enabled: yes
        state: started

    - name: Save iptables rules
      command: netfilter-persistent save

    - name: Deploy python script
      template:
        src: add_peer.py.j2
        dest: "/etc/wireguard/add_peer.py"
        mode: "0755"

    - name: Restart WireGuard to apply peer changes
      systemd:
        name: "wg-quick@{{ interface_name }}"
        state: restarted
