---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no  # Disable gathering facts
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
    
    - name: Install packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Get distribution codename
      command: lsb_release -cs
      register: dist_codename

    - name: Add Docker repository to Apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ dist_codename.stdout }} stable"
        create: yes
        insertafter: EOF
      notify:
        - Update APT repositories

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Schedule playbook to run every 5 minutes
      cron:
        name: "Run Ansible playbook every 5 minutes"
        job: "/usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/lxc/adguard.yml"
        minute: "*/5"

    - name: Schedule playbook to run at reboot
      cron:
        name: "Run Ansible playbook at reboot"
        job: "/usr/bin/ansible-pull -U https://github.com/truedem0n/homelab.git prod/ansible/lxc/adguard.yml"
        special_time: "reboot"

    - name: Create Docker volume
      docker_volume:
        name: adguard_data

    - name: Deploy Adguard Container
      docker_container:
        name: dockge
        image: adguard/adguardhome
        state: started
        restart_policy: always
        detach: yes
        ports:
          - "6060:6060/tcp"
          - "5443:5443/udp"
          - "5443:5443/tcp"
          - "853:853/udp"
          - "853:853/tcp"
          - "3000:3000/tcp"
          - "443:443/udp"
          - "443:443/tcp"
          - "80:80/tcp"
          - "68:68/udp"
          - "67:67/udp"
          - "53:53/udp"
          - "53:53/tcp"
        volumes:
          - adguard_data:/opt/adguardhome/conf\
          - adguard_data:/opt/adguardhome/work\
        container_default_behavior: 'compatibility'

    
    
