---
- name: Update and upgrade Ubuntu packages locally
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    ansible_flag_path: "/ansible/ansible_first_run.flag"
    compose_stacks:
      - speedtest.yml

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
    
    - name: Install packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Get distribution codename
      command: lsb_release -cs
      register: dist_codename

    - name: Add Docker repository to Apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ dist_codename.stdout }} stable"
        create: yes

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - nfs-common
          - nfs4-acl-tools
        state: present

    - name: Check if the flag file exists
      stat:
        path: "{{ ansible_flag_path }}"
      register: flag_file
    
    - name: Create ansible dir
      ansible.builtin.file:
        path: /ansible/
        state: directory
        mode: '0755'

    - name: Schedule playbook to run every 5 minutes
      cron:
        name: "Run Ansible playbook every 5 minutes"
        job: "/usr/bin/ansible-pull -v -U https://github.com/truedem0n/homelab.git prod/ansible/lxc/light.yml"
        minute: "*/5"

    - name: Schedule playbook to run at reboot
      cron:
        name: "Run Ansible playbook at reboot"
        job: "/usr/bin/ansible-pull -v -U https://github.com/truedem0n/homelab.git prod/ansible/lxc/light.yml"
        special_time: "reboot"


    - name: Clone the homelab repository
      git:
        repo: https://github.com/truedem0n/homelab.git
        dest: /opt/homelab
        force: true

    - name: Create Dockge docker volume
      docker_volume:
        name: dockge_data
    
    - name: Deploy Dockge Container
      docker_container:
        name: dockge
        image: louislam/dockge:latest
        state: started
        restart_policy: always
        detach: yes
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - dockge_data:/app/data
          - /mnt/data/docker/compose:/mnt/data/docker/compose
        container_default_behavior: 'compatibility'
        env:
          DOCKGE_STACKS_DIR: /mnt/data/docker/compose

    - name: Ensure /etc/fstab exists
      ansible.builtin.file:
        path: /etc/fstab
        state: touch

    - name: Create data dir
      ansible.builtin.file:
        path: /mnt/data
        state: directory
        mode: '0755'
    
    - name: Add NFS mount to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.1.30:/share/ /mnt/data nfs rw,sync,hard 0 0"
        state: present

    - name: Print link to local IP with port 5001
      ansible.builtin.debug:
        msg: "Dockge: http://{{ ansible_default_ipv4.address }}:5001"

    - name: Create the flag file
      file:
        path: "{{ ansible_flag_path }}"
        state: touch
      when: flag_file.stat.exists == false

    - name: Reboot immediately if there was a change
      ansible.builtin.command: /sbin/reboot
      when: flag_file.stat.exists == false
    
    
    
