---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - nextcloud:/config
      - /home/skylord/docker/nextcloud/data:/data
    ports:
      - 3015:443
    restart: unless-stopped

volumes:
  nextcloud:
